baseURL = "https://athul.github.io/archie/"
languageCode = "en-us"
title = "Bill Zhang"
theme="archie"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "billjhzhang"

pagination.pagerSize=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Welcome to my personal website & blog! A basic rundown: I'm currently a [Masters' of CS](https://siebelschool.illinois.edu/academics/graduate/professional-mcs) Student at the University of Illinois Urbana-Champaign (UIUC), I'm passionate about doing *cool* things with computers. To learn more about my experiences, go to [About Me](about)."
    subsubtitle = "This website is pretty empty right now. More to come soon!"
	mathjax = false # enable MathJax support
	katex = true # enable KaTeX support
    identityList = ["software engineer", "student", "photographer"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/JhaoZ"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/bill-zhang-890735209/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:billjz2@illinois.edu"

[[params.social]]
name = "Resume"
icon = "file"
url = "documents/Bill_Zhang_Resume.pdf"



# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About Me"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[security]
  enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true